version: 2

sources:
  - name: raw_retail
    database: RETAIL_DB
    schema: RAW
    tables:
      - name: customers

      - name: orders
        config:
          loaded_at_field: order_ts
          freshness:
            warn_after:
              count: 24
              period: hour
            error_after:
              count: 48
              period: hour

      - name: order_items
      - name: products
      - name: reviews
